language: node_js
node_js:
  - '8.1.4'
  - '10'

dist: trusty
sudo: false

cache: yarn

addons:
  # srcclr: true
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

after_script:
  - '[ "$TRAVIS_PULL_REQUEST" != "true" -a -n "$CODECLIMATE_REPO_TOKEN" ] && codeclimate-test-reporter < coverage/lcov.info; true'
